/**
* @Author: royce
* @Date:   2016-10-17T18:29:39-04:00
* @Email:  rharding@gotonight.com
* @Project: Go Tonight
* @Last modified by:   royce
* @Last modified time: 2016-10-19T20:37:56-04:00
* @License: © 2016 GoTonight LLC All Rights Reserved
*/

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_FORM_RESET = 'EMPLOYEE_FORM_RESET';

export const EMPLOYEE_CREATE_REQUEST = 'EMPLOYEE_CREATE_REQUEST';
export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAILED = 'EMPLOYEE_CREATE_FAILED';

export const EMPLOYEE_EDIT_REQUEST = 'EMPLOYEE_EDIT_REQUEST';
export const EMPLOYEE_EDIT_SUCCESS = 'EMPLOYEE_EDIT_SUCCESS';
export const EMPLOYEE_EDIT_FAILED = 'EMPLOYEE_EDIT_FAILED';

export const EMPLOYEES_FETCH_REQUEST = 'EMPLOYEES_FETCH_REQUEST';
export const EMPLOYEES_FETCH_SUCCESS = 'EMPLOYEES_FETCH_SUCCESS';
export const EMPLOYEES_FETCH_FAILED = 'EMPLOYEES_FETCH_FAILED';

export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST';
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
export const EMPLOYEE_DELETE_FAILED = 'EMPLOYEE_DELETE_FAILED';
